coverage:
  status:
    project:
      default:
        target: 85%
    patch:
      default:
        target: 85%

# Optionally require CI to pass before reporting
# codecov:
#   require_ci_to_pass: yes
